/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;

import javax.swing.JOptionPane;


public class AddBudgetGui extends javax.swing.JFrame {
    private Client temp;
    
    /**
     * Creates new form AddBudget
     */
    public AddBudgetGui(Client x) {
        initComponents();
        temp = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBName = new javax.swing.JTextField();
        txtBDesp = new javax.swing.JTextField();
        txtEst = new javax.swing.JTextField();
        txtEstDate = new javax.swing.JTextField();

        setTitle("Add Budget");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBbtn.setText("Add Budget");
        addBbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel1.setText("Budget Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel2.setText("Budget Description:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setText("Estimate:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel4.setText("Estimate Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        getContentPane().add(txtBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 150, 20));
        getContentPane().add(txtBDesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, 20));
        getContentPane().add(txtEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 150, 20));
        getContentPane().add(txtEstDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, 20));

        setBounds(0, 0, 414, 340);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Add budget window
    */
    private void addBbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBbtnActionPerformed
        String a = txtBName.getText().trim();
        String b = txtBDesp.getText().trim();
        String z = txtEst.getText().trim();
        try {
        int c = Integer.parseInt(z);
        String d = txtEstDate.getText();
        Budget b1 = new Budget(a,b,c,d);
	temp.addBudget(b1);
        this.setVisible(false);
        ClientGui.update(temp);
        }
        catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(null, "Estimate entered is not a number."); 
        }
        
    }//GEN-LAST:event_addBbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddBudgetGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtBDesp;
    private javax.swing.JTextField txtBName;
    private javax.swing.JTextField txtEst;
    private javax.swing.JTextField txtEstDate;
    // End of variables declaration//GEN-END:variables
}
