/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;



public class AddClientGui extends javax.swing.JFrame {

    /**
     * Creates new form AddClientGui
     */
    public AddClientGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addClientbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        txtCNumber = new javax.swing.JTextField();
        txtCAddress = new javax.swing.JTextField();

        setTitle("Add Client");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addClientbtn.setText("Add Client");
        addClientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addClientbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel1.setText("Client Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setText("Phone Number:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("Address:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));
        getContentPane().add(txtCName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 150, 20));

        txtCNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtCNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, 20));
        getContentPane().add(txtCAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, 20));

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Add client window
    */
    private void addClientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientbtnActionPerformed
        String a = txtCName.getText().trim();
        String b = txtCNumber.getText().trim();
        String c = txtCAddress.getText().trim();
        Client c1 = new Client(a,b,c);
	Account.addClient(c1);
        this.setVisible(false);
        AccountGui.update();
    }//GEN-LAST:event_addClientbtnActionPerformed

    private void txtCNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddClientGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCAddress;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCNumber;
    // End of variables declaration//GEN-END:variables

}
