/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;

import javax.swing.JOptionPane;


public class AddExpenseGui extends javax.swing.JFrame {
    private Budget temp;
    
    /**
     * Creates new form AddExpenseGui
     */
    public AddExpenseGui(Budget x) {
        initComponents();
        temp = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addExpbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtExpName = new javax.swing.JTextField();
        txtExpValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Add Expense");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addExpbtn.setText("Add Expense");
        addExpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExpbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addExpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel1.setText("Expense Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        getContentPane().add(txtExpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 150, 20));
        getContentPane().add(txtExpValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 20));

        jLabel2.setText("Expense Value:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        setBounds(0, 0, 414, 341);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Add expense window
    */
    private void addExpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpbtnActionPerformed
        String a = txtExpName.getText().trim();
        String c = txtExpValue.getText().trim();
        try {
        int b = Integer.parseInt(c);
        Expense e1 = new Expense(a,b);
	temp.addExpense(e1);
        this.setVisible(false);
        BudgetGui.update(temp);
        }
        catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(null, "Expense value entered is not a number."); 
        }
    }//GEN-LAST:event_addExpbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExpenseGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExpenseGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExpenseGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExpenseGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddExpenseGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtExpName;
    private javax.swing.JTextField txtExpValue;
    // End of variables declaration//GEN-END:variables
}
