/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;

import javax.swing.JOptionPane;


public class AddPayGui extends javax.swing.JFrame {
    private Budget temp;
    
    /**
     * Creates new form AddPayGui
     */
    public AddPayGui(Budget x) {
        initComponents();
        temp = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPaybtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPayName = new javax.swing.JTextField();
        txtPayValue = new javax.swing.JTextField();
        txtPayDate = new javax.swing.JTextField();

        setTitle("Add Payment");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addPaybtn.setText("Add Payment");
        addPaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaybtnActionPerformed(evt);
            }
        });
        getContentPane().add(addPaybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel1.setText("Payment Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel2.setText("Payment Value:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel3.setText("Payment Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        getContentPane().add(txtPayName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 150, 20));
        getContentPane().add(txtPayValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, 20));
        getContentPane().add(txtPayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, 20));

        setBounds(0, 0, 416, 340);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Add payment window
    */
    private void addPaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaybtnActionPerformed
        String a = txtPayName.getText().trim();
        String d = txtPayValue.getText().trim();
        try {
        int b = Integer.parseInt(d);
        String c = txtPayDate.getText();
        Payment p1 = new Payment(a,b,c);
	temp.addPayment(p1);
        this.setVisible(false);
        BudgetGui.update(temp);
        }
        catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(null, "Payment value entered is not a number."); 
        }
    }//GEN-LAST:event_addPaybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddPayGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPaybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPayDate;
    private javax.swing.JTextField txtPayName;
    private javax.swing.JTextField txtPayValue;
    // End of variables declaration//GEN-END:variables
}
