/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;


public class BudgetGui extends javax.swing.JFrame {
    private Budget temp;
    
    /**
     * Creates new form BudgetGui
     */
    public BudgetGui(Budget x) {
        initComponents();
        temp = x;
        update(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        detailListing = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        expMenu = new javax.swing.JMenu();
        addE = new javax.swing.JMenuItem();
        removeE = new javax.swing.JMenuItem();
        modifyE = new javax.swing.JMenuItem();
        payMenu = new javax.swing.JMenu();
        addP = new javax.swing.JMenuItem();
        removeP = new javax.swing.JMenuItem();
        modifyP = new javax.swing.JMenuItem();

        setTitle("Budget Details");

        detailListing.setColumns(20);
        detailListing.setRows(5);
        jScrollPane1.setViewportView(detailListing);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        expMenu.setText("Expense Menu");

        addE.setText("Add Expense");
        addE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEActionPerformed(evt);
            }
        });
        expMenu.add(addE);

        removeE.setText("Remove Expense");
        removeE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEActionPerformed(evt);
            }
        });
        expMenu.add(removeE);

        modifyE.setText("Modify Expense");
        modifyE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyEActionPerformed(evt);
            }
        });
        expMenu.add(modifyE);

        jMenuBar1.add(expMenu);

        payMenu.setText("Payment Menu");

        addP.setText("Add Payment");
        addP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPActionPerformed(evt);
            }
        });
        payMenu.add(addP);

        removeP.setText("Remove Payment");
        removeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePActionPerformed(evt);
            }
        });
        payMenu.add(removeP);

        modifyP.setText("Modify Payment");
        modifyP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPActionPerformed(evt);
            }
        });
        payMenu.add(modifyP);

        jMenuBar1.add(payMenu);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 496, 352);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Add expense window
    */
    private void addEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEActionPerformed
         new AddExpenseGui(temp).setVisible(true);
    }//GEN-LAST:event_addEActionPerformed

    /*
    * Remove expense window
    */
    private void removeEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEActionPerformed
         new RemoveExpenseGui(temp).setVisible(true);
    }//GEN-LAST:event_removeEActionPerformed

    /*
    * Modify expense window
    */
    private void modifyEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyEActionPerformed
         new ModifyExpenseGui(temp).setVisible(true);
    }//GEN-LAST:event_modifyEActionPerformed

    /*
    * Add payment window
    */
    private void addPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPActionPerformed
         new AddPayGui(temp).setVisible(true);
    }//GEN-LAST:event_addPActionPerformed

    /*
    * Remove payment window
    */
    private void removePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePActionPerformed
         new RemovePayGui(temp).setVisible(true);
    }//GEN-LAST:event_removePActionPerformed

    /*
    * Modify payment window
    */
    private void modifyPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPActionPerformed
         new ModifyPayGui(temp).setVisible(true);
    }//GEN-LAST:event_modifyPActionPerformed

   /*
    * updates budget display window
    * @param x current budget
    */
    public static void update (Budget x) {
        detailListing.setText(x.BudDetails());        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new BudgetGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addE;
    private javax.swing.JMenuItem addP;
    private static javax.swing.JTextArea detailListing;
    private javax.swing.JMenu expMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem modifyE;
    private javax.swing.JMenuItem modifyP;
    private javax.swing.JMenu payMenu;
    private javax.swing.JMenuItem removeE;
    private javax.swing.JMenuItem removeP;
    // End of variables declaration//GEN-END:variables
}
