/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;


public class ClientGui extends javax.swing.JFrame {
//    private static ArrayList <Budget> bud;
    private Client temp;
    /**
     * Creates new form ClientGui
     */
    public ClientGui(Client x) {
        initComponents();
        temp = x;
        update(x);
        
//        bud = new ArrayList <Budget> ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        budListing = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        editC = new javax.swing.JMenu();
        addB = new javax.swing.JMenuItem();
        removeB = new javax.swing.JMenuItem();
        modifyB = new javax.swing.JMenuItem();
        accessEP = new javax.swing.JMenuItem();

        setTitle("Budgets");

        budListing.setColumns(20);
        budListing.setRows(5);
        jScrollPane1.setViewportView(budListing);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        editC.setText("Menu");

        addB.setText("Add Budget");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });
        editC.add(addB);

        removeB.setText("Remove Budget");
        removeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBActionPerformed(evt);
            }
        });
        editC.add(removeB);

        modifyB.setText("Modify Budget");
        modifyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBActionPerformed(evt);
            }
        });
        editC.add(modifyB);

        accessEP.setText("Access Expenses/Payments ");
        accessEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessEPActionPerformed(evt);
            }
        });
        editC.add(accessEP);

        jMenuBar1.add(editC);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 554, 359);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Remove budget window
    */
    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed
         new RemoveBudgetGui(temp).setVisible(true);
    }//GEN-LAST:event_removeBActionPerformed

    /*
    * Add budget window
    */
    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
         new AddBudgetGui(temp).setVisible(true);
    }//GEN-LAST:event_addBActionPerformed

    /*
    * Modify budget window
    */
    private void modifyBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBActionPerformed
         new ModifyBudgetGui(temp).setVisible(true);
    }//GEN-LAST:event_modifyBActionPerformed

    /*
    * Access exp/pay window
    */
    private void accessEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessEPActionPerformed
         new AccessEPGui(temp).setVisible(true);
    }//GEN-LAST:event_accessEPActionPerformed

    /*
    * updates budget display window
    * @param x current Client
    */
    public static void update (Client x) {
        budListing.setText(x.BudgetList());        
    }
    
//    public static void setBudget (ArrayList <Budget> z) {
//        ClientGui.bud = z;
//    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ClientGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem accessEP;
    private javax.swing.JMenuItem addB;
    private static javax.swing.JTextArea budListing;
    private javax.swing.JMenu editC;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem modifyB;
    private javax.swing.JMenuItem removeB;
    // End of variables declaration//GEN-END:variables
}
