/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;

import javax.swing.JOptionPane;


public class ModifyPayGui extends javax.swing.JFrame {
    private Budget temp;
    
    /**
     * Creates new form ModifyPayGui
     */
    public ModifyPayGui(Budget x) {
        initComponents();
        temp = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modPaybtn = new javax.swing.JButton();
        txtOGName = new javax.swing.JTextField();
        txtMName = new javax.swing.JTextField();
        txtMValue = new javax.swing.JTextField();
        txtMDate = new javax.swing.JTextField();

        setTitle("Modify Payment");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Original Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel2.setText("Modified Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel3.setText("Modified Value:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel4.setText("Modified Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        modPaybtn.setText("Modify Payment");
        modPaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modPaybtnActionPerformed(evt);
            }
        });
        getContentPane().add(modPaybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        getContentPane().add(txtOGName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 150, 20));
        getContentPane().add(txtMName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 20));
        getContentPane().add(txtMValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 20));
        getContentPane().add(txtMDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 150, 20));

        setBounds(0, 0, 415, 339);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Modify payment window
    */
    private void modPaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modPaybtnActionPerformed
        String a = txtOGName.getText().trim();
        String b = txtMName.getText().trim();
        String z = txtMValue.getText().trim();
        try {
        int c = Integer.parseInt(z);
        String d = txtMValue.getText();
        Payment p1 = new Payment(b,c,d);
        temp.modifyPay(a,p1);
        this.setVisible(false);
        BudgetGui.update(temp);
        }
        catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(null, "Payment value entered is not a number."); 
        }
    }//GEN-LAST:event_modPaybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ModifyPayGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton modPaybtn;
    private javax.swing.JTextField txtMDate;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMValue;
    private javax.swing.JTextField txtOGName;
    // End of variables declaration//GEN-END:variables
}
