/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;

import javax.swing.JOptionPane;


public class ModifyBudgetGui extends javax.swing.JFrame {
    private Client temp;
    
    /**
     * Creates new form ModifyBudget
     */
    public ModifyBudgetGui(Client x) {
        initComponents();
        temp = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifyBbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOGName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDsp = new javax.swing.JTextField();
        txtEst = new javax.swing.JTextField();
        txtEstDate = new javax.swing.JTextField();

        setTitle("Modify Budget");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyBbtn.setText("Modify Budget");
        modifyBbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBbtnActionPerformed(evt);
            }
        });
        getContentPane().add(modifyBbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel1.setText("Original Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel2.setText("Modified Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 20));

        jLabel3.setText("Modified Description:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setText("Modified Estimate:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setText("Modified Estimate Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        getContentPane().add(txtOGName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 150, 20));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150, 20));
        getContentPane().add(txtDsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 150, 20));
        getContentPane().add(txtEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 150, 20));
        getContentPane().add(txtEstDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 150, 20));

        setSize(new java.awt.Dimension(414, 344));
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Modify budget window
    */
    private void modifyBbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBbtnActionPerformed
        String a = txtOGName.getText().trim();
        String b = txtName.getText().trim();
        String c = txtDsp.getText().trim();
        String f = txtEst.getText().trim();
        try {
        int d = Integer.parseInt(f);
        String e = txtEstDate.getText();
        Budget b1 = new Budget(b,c,d,e);
        temp.modifyBudget(a,b1);
        this.setVisible(false);
        ClientGui.update(temp);
        }
        catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(null, "Estimate entered is not a number."); 
        }
    }//GEN-LAST:event_modifyBbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ModifyBudgetGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton modifyBbtn;
    private javax.swing.JTextField txtDsp;
    private javax.swing.JTextField txtEst;
    private javax.swing.JTextField txtEstDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOGName;
    // End of variables declaration//GEN-END:variables
}
