/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;

import javax.swing.JOptionPane;


public class ModifyExpenseGui extends javax.swing.JFrame {
    private Budget temp;
    
    /**
     * Creates new form ModifyExpenseGui
     */
    public ModifyExpenseGui(Budget x) {
        initComponents();
        temp = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifyExpbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOGName = new javax.swing.JTextField();
        txtMName = new javax.swing.JTextField();
        txtMValue = new javax.swing.JTextField();

        setTitle("Modify Expense");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyExpbtn.setText("Modify Expense");
        modifyExpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyExpbtnActionPerformed(evt);
            }
        });
        getContentPane().add(modifyExpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel1.setText("Original Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel2.setText("Modified Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel3.setText("Modified Value:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        getContentPane().add(txtOGName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 150, 20));
        getContentPane().add(txtMName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, 20));
        getContentPane().add(txtMValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 20));

        setBounds(0, 0, 414, 335);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Modify expense window
    */
    private void modifyExpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyExpbtnActionPerformed
        String a = txtOGName.getText().trim();
        String b = txtMName.getText().trim();
        String d = txtMValue.getText().trim();
        try {
        int c = Integer.parseInt(d);
        Expense e1 = new Expense(b,c);
        temp.modifyExp(a,e1);
        this.setVisible(false);
        BudgetGui.update(temp);
        }
        catch (NumberFormatException e) {
           JOptionPane.showMessageDialog(null, "Expense value entered is not a number."); 
        }
    }//GEN-LAST:event_modifyExpbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyExpenseGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyExpenseGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyExpenseGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyExpenseGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ModifyExpenseGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton modifyExpbtn;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMValue;
    private javax.swing.JTextField txtOGName;
    // End of variables declaration//GEN-END:variables
}
