/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;


public class ModifyClientGui extends javax.swing.JFrame {

    /**
     * Creates new form ModifyClientGui
     */
    public ModifyClientGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modifyCbin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOGName = new javax.swing.JTextField();
        txtMName = new javax.swing.JTextField();
        txtMNumber = new javax.swing.JTextField();
        txtMAddress = new javax.swing.JTextField();

        setTitle("Modify Client");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifyCbin.setText("Modify Client");
        modifyCbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyCbinActionPerformed(evt);
            }
        });
        getContentPane().add(modifyCbin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel1.setText("Original Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setText("Modified Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setText("Modified Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setText("Modified Address:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        getContentPane().add(txtOGName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 150, 20));
        getContentPane().add(txtMName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, 20));
        getContentPane().add(txtMNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 150, 20));
        getContentPane().add(txtMAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 150, 20));

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Modify client window
    */
    private void modifyCbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyCbinActionPerformed
        String a = txtOGName.getText().trim();
        String b = txtMName.getText().trim();
        String c = txtMNumber.getText().trim();
        String d = txtMAddress.getText().trim();
        Client c1 = new Client(b,c,d);
        Account.modifyClient(a,c1);
        this.setVisible(false);
        AccountGui.update();
    }//GEN-LAST:event_modifyCbinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyClientGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ModifyClientGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton modifyCbin;
    private javax.swing.JTextField txtMAddress;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMNumber;
    private javax.swing.JTextField txtOGName;
    // End of variables declaration//GEN-END:variables
}
