/*
 * Sherry Hayes
 * Project - Part 3
 * Computer Science - CS 234
 */
package com.mycompany.csiiproject;


public class RemoveBudgetGui extends javax.swing.JFrame {
    private Client temp;
    /**
     * Creates new form RemoveBudget
     */
    public RemoveBudgetGui(Client x) {
        initComponents();
        temp = x;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeBbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBName = new javax.swing.JTextField();

        setTitle("Remove Budget");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeBbtn.setText("Remove Budget");
        removeBbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBbtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeBbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel1.setText("Budget Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 20));

        setBounds(0, 0, 398, 338);
    }// </editor-fold>//GEN-END:initComponents

    /*
    * Remove budget window
    */
    private void removeBbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBbtnActionPerformed
        String a = txtBName.getText().trim();
        temp.removeBudget(a);
        this.setVisible(false);
        ClientGui.update(temp);
    }//GEN-LAST:event_removeBbtnActionPerformed

    private void txtBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveBudgetGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RemoveBudgetGui().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton removeBbtn;
    private javax.swing.JTextField txtBName;
    // End of variables declaration//GEN-END:variables
}
